version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: chat_rabbitmq_broker
    ports:
      - "5672:5672"    # Port protokołu AMQP
      - "15672:15672"  # Port panelu administracyjnego
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - chat_network

volumes:
  rabbitmq_data:

networks:
  chat_network: